# This file was generated by GoReleaser. DO NOT EDIT.
class Gitprompt < Formula
  desc "git status in the prompt"
  homepage "https://github.com/akupila/gitprompt"
  url "https://github.com/akupila/gitprompt/releases/download/v0.2.1/gitprompt_0.2.1_darwin_amd64.tar.gz"
  version "0.2.1"
  sha256 "ddc45c4c5663338519e6b1f4e302ed456da5ee308c69aa8cd7836b9e424516a5"

  def install
    bin.install "gitprompt"
  end
end
